name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update firmware version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Setting firmware version to $VERSION"
          sed -i "s/#define FIRMWARE_VERSION .*/#define FIRMWARE_VERSION \"$VERSION\"/" include/version.h

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Build filesystem
        run: pio run -t buildfs

      - name: Prepare binaries
        run: |
          mkdir -p binaries
          cp .pio/build/*/*.bin binaries/ || true

      - name: Sign firmware with ECDSA
        run: |
          echo "$FW_SIGNING_KEY" > ec_private.pem
          for fw in binaries/*.bin; do
            echo "Signing $fw"
            openssl dgst -sha256 -sign ec_private.pem -out "${fw}.sig" "$fw"
          done
          rm ec_private.pem
        env:
          FW_SIGNING_KEY: ${{ secrets.FW_SIGNING_KEY }}

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
